# Reference database for the NCS draft. Keys are cited in the manuscript as {{key}}.
# Entries added for the NCS version (mup, depthmup, bordelon, logitlens, tunedlens, meng, heimersheim, laco, wanda, calm, mod, tishby, saxeib, jacobiansae, semedo) were checked against arXiv, ACL Anthology, Cell and NeurIPS/ICLR listings on 20 Sept 2026.

REFS = {
 "glorot": "Glorot, X. & Bengio, Y. Understanding the difficulty of training deep feedforward neural networks. In Proc. 13th International Conference on Artificial Intelligence and Statistics (AISTATS), PMLR 9, 249–256 (2010).",
 "poole": "Poole, B., Lahiri, S., Raghu, M., Sohl-Dickstein, J. & Ganguli, S. Exponential expressivity in deep neural networks through transient chaos. In Advances in Neural Information Processing Systems 29, 3360–3368 (2016).",
 "pennington": "Pennington, J., Schoenholz, S. S. & Ganguli, S. Resurrecting the sigmoid in deep learning through dynamical isometry: theory and practice. In Advances in Neural Information Processing Systems 30 (2017).",
 "schoenholz": "Schoenholz, S. S., Gilmer, J., Ganguli, S. & Sohl-Dickstein, J. Deep information propagation. In Proc. International Conference on Learning Representations (2017).",
 "saxe": "Saxe, A. M., McClelland, J. L. & Ganguli, S. Exact solutions to the nonlinear dynamics of learning in deep linear neural networks. In Proc. International Conference on Learning Representations (2014).",
 "yangschoenholz": "Yang, G. & Schoenholz, S. Mean field residual networks: on the edge of chaos. In Advances in Neural Information Processing Systems 30 (2017).",
 "hanin": "Hanin, B. & Nica, M. Products of many large random matrices and gradients in deep neural networks. Commun. Math. Phys. 376, 287–322 (2020).",
 "mup": "Yang, G. et al. Tensor Programs V: tuning large neural networks via zero-shot hyperparameter transfer. In Advances in Neural Information Processing Systems 34 (2021).",
 "depthmup": "Yang, G., Yu, D., Zhu, C. & Hayou, S. Tensor Programs VI: feature learning in infinite-depth neural networks. In Proc. International Conference on Learning Representations (2024).",
 "bordelon": "Bordelon, B., Noci, L., Li, M. B., Hanin, B. & Pehlevan, C. Depthwise hyperparameter transfer in residual networks: dynamics and scaling limit. In Proc. International Conference on Learning Representations (2024).",
 "zhanglayers": "Zhang, C., Bengio, S. & Singer, Y. Are all layers created equal? J. Mach. Learn. Res. 23, 1–28 (2022).",
 "lipapyan": "Li, J. & Papyan, V. Residual alignment: uncovering the mechanisms of residual networks. In Advances in Neural Information Processing Systems 36 (2023).",
 "fernando": "Fernando, J. & Guitchounts, G. Dynamics of the transformer residual stream: coupling spectral geometry to network topology. Preprint at https://arxiv.org/abs/2605.14258 (2026).",
 "jing": "Jing, T. et al. Beyond layer importance in layer-wise sparsity: an inter-layer perturbation-absorption perspective. Preprint at https://arxiv.org/abs/2606.15161 (2026).",
 "aubry": "Aubry, M., Meng, H., Sugolov, A. & Papyan, V. Transformer block coupling and its correlation with generalization in LLMs. In Proc. International Conference on Learning Representations (2025).",
 "tenney": "Tenney, I., Das, D. & Pavlick, E. BERT rediscovers the classical NLP pipeline. In Proc. 57th Annual Meeting of the Association for Computational Linguistics, 4593–4601 (2019).",
 "raghu": "Raghu, M., Gilmer, J., Yosinski, J. & Sohl-Dickstein, J. SVCCA: singular vector canonical correlation analysis for deep learning dynamics and interpretability. In Advances in Neural Information Processing Systems 30, 6076–6085 (2017).",
 "kornblith": "Kornblith, S., Norouzi, M., Lee, H. & Hinton, G. Similarity of neural network representations revisited. In Proc. 36th International Conference on Machine Learning, PMLR 97, 3519–3529 (2019).",
 "logitlens": "nostalgebraist. Interpreting GPT: the logit lens. LessWrong (2020).",
 "tunedlens": "Belrose, N. et al. Eliciting latent predictions from transformers with the tuned lens. Preprint at https://arxiv.org/abs/2303.08112 (2023).",
 "elhage": "Elhage, N. et al. A mathematical framework for transformer circuits. Transformer Circuits Thread (2021).",
 "meng": "Meng, K., Bau, D., Andonian, A. & Belinkov, Y. Locating and editing factual associations in GPT. In Advances in Neural Information Processing Systems 35 (2022).",
 "heimersheim": "Heimersheim, S. & Nanda, N. How to use and interpret activation patching. Preprint at https://arxiv.org/abs/2404.15255 (2024).",
 "gromov": "Gromov, A., Tirumala, K., Shapourian, H., Glorioso, P. & Roberts, D. A. The unreasonable ineffectiveness of the deeper layers. In Proc. International Conference on Learning Representations (2025).",
 "shortgpt": "Men, X. et al. ShortGPT: layers in large language models are more redundant than you expect. In Findings of the Association for Computational Linguistics: ACL 2025, 20192–20204 (2025).",
 "laco": "Yang, Y., Cao, Z. & Zhao, H. LaCo: large language model pruning via layer collapse. In Findings of the Association for Computational Linguistics: EMNLP 2024 (2024).",
 "wanda": "Sun, M., Liu, Z., Bair, A. & Kolter, J. Z. A simple and effective pruning approach for large language models. In Proc. International Conference on Learning Representations (2024).",
 "calm": "Schuster, T. et al. Confident adaptive language modeling. In Advances in Neural Information Processing Systems 35 (2022).",
 "mod": "Raposo, D. et al. Mixture-of-Depths: dynamically allocating compute in transformer-based language models. Preprint at https://arxiv.org/abs/2404.02258 (2024).",
 "tishby": "Tishby, N. & Zaslavsky, N. Deep learning and the information bottleneck principle. In Proc. IEEE Information Theory Workshop (2015).",
 "saxeib": "Saxe, A. M. et al. On the information bottleneck theory of deep learning. In Proc. International Conference on Learning Representations (2018).",
 "he": "He, K., Zhang, X., Ren, S. & Sun, J. Deep residual learning for image recognition. In Proc. IEEE Conference on Computer Vision and Pattern Recognition, 770–778 (2016).",
 "balduzzi": "Balduzzi, D. et al. The shattered gradients problem: if resnets are the answer, then what is the question? In Proc. 34th International Conference on Machine Learning, PMLR 70, 342–350 (2017).",
 "veit": "Veit, A., Wilber, M. & Belongie, S. Residual networks behave like ensembles of relatively shallow networks. In Advances in Neural Information Processing Systems 29 (2016).",
 "vaswani": "Vaswani, A. et al. Attention is all you need. In Advances in Neural Information Processing Systems 30, 5998–6008 (2017).",
 "radford": "Radford, A. et al. Language models are unsupervised multitask learners. Technical Report (OpenAI, 2019).",
 "biderman": "Biderman, S. et al. Pythia: a suite for analyzing large language models across training and scaling. In Proc. 40th International Conference on Machine Learning, PMLR 202, 2397–2430 (2023).",
 "qwen": "Yang, A. et al. Qwen2.5 technical report. Preprint at https://arxiv.org/abs/2412.15115 (2024).",
 "phi2": "Javaheripi, M. et al. Phi-2: the surprising power of small language models. Microsoft Research Blog (2023).",
 "llama3": "Llama Team. The Llama 3 herd of models. Preprint at https://arxiv.org/abs/2407.21783 (2024).",
 "mistral": "Jiang, A. Q. et al. Mistral 7B. Preprint at https://arxiv.org/abs/2310.06825 (2023).",
 "gemma": "Gemma Team. Gemma 2: improving open language models at a practical size. Preprint at https://arxiv.org/abs/2408.00118 (2024).",
 "devlin": "Devlin, J., Chang, M.-W., Lee, K. & Toutanova, K. BERT: pre-training of deep bidirectional transformers for language understanding. In Proc. NAACL-HLT, 4171–4186 (2019).",
 "roberta": "Liu, Y. et al. RoBERTa: a robustly optimized BERT pretraining approach. Preprint at https://arxiv.org/abs/1907.11692 (2019).",
 "mamba": "Gu, A. & Dao, T. Mamba: linear-time sequence modeling with selective state spaces. In Proc. Conference on Language Modeling (2024).",
 "convnext": "Liu, Z. et al. A ConvNet for the 2020s. In Proc. IEEE/CVF Conference on Computer Vision and Pattern Recognition, 11976–11986 (2022).",
 "dinov2": "Oquab, M. et al. DINOv2: learning robust visual features without supervision. Trans. Mach. Learn. Res. (2024).",
 "vit": "Dosovitskiy, A. et al. An image is worth 16×16 words: transformers for image recognition at scale. In Proc. International Conference on Learning Representations (2021).",
 "whisper": "Radford, A. et al. Robust speech recognition via large-scale weak supervision. In Proc. 40th International Conference on Machine Learning, PMLR 202, 28492–28518 (2023).",
 "cifar": "Krizhevsky, A. Learning multiple layers of features from tiny images. Technical Report (University of Toronto, 2009).",
 "librispeech": "Panayotov, V., Chen, G., Povey, D. & Khudanpur, S. LibriSpeech: an ASR corpus based on public domain audio books. In Proc. IEEE International Conference on Acoustics, Speech and Signal Processing, 5206–5210 (2015).",
 "merity": "Merity, S., Xiong, C., Bradbury, J. & Socher, R. Pointer sentinel mixture models. In Proc. International Conference on Learning Representations (2017).",
 "raffel": "Raffel, C. et al. Exploring the limits of transfer learning with a unified text-to-text transformer. J. Mach. Learn. Res. 21, 1–67 (2020).",
 "unet": "Ronneberger, O., Fischer, P. & Brox, T. U-Net: convolutional networks for biomedical image segmentation. In Medical Image Computing and Computer-Assisted Intervention (MICCAI 2015), LNCS 9351, 234–241 (2015).",
 "hartigan": "Hartigan, J. A. & Hartigan, P. M. The dip test of unimodality. Ann. Stat. 13, 70–84 (1985).",
 "imagenet": "Deng, J. et al. ImageNet: a large-scale hierarchical image database. In Proc. IEEE Conference on Computer Vision and Pattern Recognition, 248–255 (2009).",
 "jacobiansae": "Farnik, L. et al. Jacobian sparse autoencoders: sparsify computations, not just activations. Preprint at https://arxiv.org/abs/2502.18147 (2025).",
 "semedo": "Semedo, J. D., Zandvakili, A., Machens, C. K., Yu, B. M. & Kohn, A. Cortical areas interact through a communication subspace. Neuron 102, 249–259 (2019).",
 "fishback": "Wang, S., Zhao, J., Cao, Q., Yao, H. & Shu, L. FishBack: pullback Fisher geometry for optimal activation steering in transformers. Preprint at https://arxiv.org/abs/2605.17231 (2026).",
 "basu": "Basu, A., Basu, K. & Deb, K. Structural sensitivity in compressed transformers: relative error propagation and layer removal. Preprint at https://arxiv.org/abs/2603.20991 (2026).",
 "raghavan": "Raghavan, G., Tharwat, B., Hari, S. N., Satani, D., Liu, R. & Thomson, M. Engineering flexible machine learning systems by traversing functionally invariant paths. Nat. Mach. Intell. 6, 1179–1196 (2024).",
 "semanticlens": "Dreyer, M. et al. Mechanistic understanding and validation of large AI models with SemanticLens. Nat. Mach. Intell. 7, 1572–1585 (2025).",
}
